import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Profile from '@/components/Props/index'
import { useState } from 'react'
import Properties from "@/components/Props/props"

const inter = Inter({ subsets: ['latin'] }) 

  export default function Home(props: Properties) {

    const [persons, setPersons] = useState([
      {
          subject: "Gustavo",
          ImageId: "0101"
      },
      {
          subject:"Artur",
          ImageId: "01010101"
      }
    ]);

    const handleClick = () => {
      if(persons[0].subject) {
        setPersons(persons[1].subject)
      }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Profile
          handleClick={handleClick}
          subject={nome[0].subject}
          ImageId={nome[0].ImageId}
        />
      </main>
    </>
  )
}


