import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Profile from '@/components/Props'
import { useState } from 'react'
import Properties from "@/components/Props/props"

const inter = Inter({ subsets: ['latin'] })

let nome = [
  {
      subject: "Gustavo",
      ImageId: "0101"
  },
  {
      subject:"Artur",
      ImageId: "01010101"
  }
]

  export default function Home(props: Properties) {

    const [nomeChange, setnomeChange] = useState(nome[0].subject);
    const [imageIdChange, setimageIdChange] = useState(nome[0].ImageId)

    const handleClick = () => {
      if (nomeChange == nome[0].subject) {
          setnomeChange(nome[1].subject);
      } else {
          setnomeChange(nome[0].subject)
      }

      if(imageIdChange == nome[0].ImageId) {
          setimageIdChange(nome[1].ImageId)
      } else {
          setimageIdChange(nome[0].ImageId)
      }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Profile
          handleClick={handleClick}
          subject={nome[0].subject}
          ImageId={nome[0].ImageId}
        />
      </main>
    </>
  )
}


